version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - './pgdata:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: adonisjs
    ports:
      - '5432:5432'
